version: 2.1
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    working_directory: ~/SampleUnitTest-MATLAB
    machine:
      image: 'ubuntu-2204:2022.07.1'
    steps:
      - checkout
      - run:
          command: |
            echo 'export PATH=~/SampleUnitTest-MATLAB/src:"$PATH"' >> "$MATLABPATH"
            source "$MATLABPATH"
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
      - store_test_results:
          path: test-results
workflows:
  build:
    jobs:
      - build
