version: 2.1
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    machine:
      image: 'ubuntu-2204:2022.07.1'
    steps:
      - checkout
      - run
          environment:
            MATLABPATH: /home/circleci/project/src 
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
      - store_test_results:
          path: test-results
workflows:
  build:
    jobs:
      - build
